[project]
name = "boto3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kaifvymxb-netizen", email = "kaifvy.mx.b@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
boto3 = "boto3:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
