#!/usr/bin/env python3                                                                                                                                                                                                                       
"""List all objects in a specified S3 bucket using boto3."""                                                                                                                                                                                 
# I wasn't sure if you wanted me to write a function that would list all objects in every bucket, or just a specified bucket.                                                                                                                                                                                                                                              
import argparse                                                                                                                                                                                                                              
import sys                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                
import boto3                                                                                                                                                                                                                                 
from botocore.exceptions import NoCredentialsError, ClientError                                                                                                                                                                              
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
def list_s3_objects(bucket_name: str) -> None:                                                                                                                                                                                               
       """List all object keys in the given S3 bucket and write them to mybuckets.txt."""                                                                                                                                                       
       s3 = boto3.client("s3")                                                                                                                                                                                                                  
       try:                                                                                                                                                                                                                                     
           paginator = s3.get_paginator("list_objects_v2")                                                                                                                                                                                      
           page_iterator = paginator.paginate(Bucket=bucket_name)                                                                                                                                                                               
                                                                                                                                                                                                                                                
           with open("mybucket.txt", "w") as f:                                                                                                                                                                                                
               object_count = 0    
               f.write(f'\nBucket: {bucket_name}\n')                                                                                                                                                                                                             
               for page in page_iterator:                                                                                                                                                                                                       
                   contents = page.get("Contents", [])                                                                                                                                                                                          
                   for obj in contents:                                                                                                                                                                                                         
                       f.write(obj["Key"] + "\n")                                                                                                                                                                                               
                       object_count += 1                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
               if object_count == 0:                                                                                                                                                                                                            
                   f.write("(bucket is empty or no objects found)\n")                                                                                                                                                                           
                                                                                                                                                                                                                                                
       except NoCredentialsError:                                                                                                                                                                                                               
           print("Error: No AWS credentials found. Configure your credentials.")                                                                                                                                                                
           sys.exit(1)                                                                                                                                                                                                                          
       except ClientError as e:                                                                                                                                                                                                                 
           print(f"Error: {e}")                                                                                                                                                                                                                 
           sys.exit(1)                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
if __name__ == "__main__":                                                                                                                                                                                                                   
       parser = argparse.ArgumentParser(                                                                                                                                                                                                        
           description="List all objects in an S3 bucket."                                                                                                                                                                                      
       )                                                                                                                                                                                                                                        
       parser.add_argument(                                                                                                                                                                                                                     
           "--bucket",                                                                                                                                                                                                                          
           required=False,                                                                                                                                                                                                                       
           help="Name of the S3 bucket to list objects from.",                                                                                                                                                                                  
       )                                                                                                                                                                                                                                        
       args = parser.parse_args()                                                                                                                                                                                                               
                                                                                                                                                                                                                                                
       list_s3_objects(args.bucket)  